### PR TITLE
fix: non-netlify dependencies moved to devdependency

### PR DESCRIPTION
**Pull request by sean-pwd**
Dependencies required for netlify moved to dependencies. 

Dependencies NOT required for netlifly left in devDependencies. 

NPM flag added to netlify.toml     NPM_FLAGS = "--production"
equivalent of npm install --production 

https://docs.netlify.com/configure-builds/manage-dependencies/
You can customize your npm use with the following environment variables:
NPM_FLAGS: flags to pass to the npm install command.

https://docs.npmjs.com/cli/v7/commands/npm-install
With the --production flag (or when the NODE_ENV environment variable is set to production), npm will not install modules listed in devDependencies.

### CODE REVIEW

**Review by h-enk — CHANGES_REQUESTED** [review]
It fails on `hugo-installer: not found` (see also https://app.netlify.com/sites/hyas/deploys/60fabf67dd56741d8b866029). So. make hugo-installer a dependency again?

**Comment by sean-pwd** [comment]
I have to check it tomorrow.. I'll work it out. Thanks for letting me know

**Comment by sean-pwd** [comment]
I had a look and netlify is running NPM INSTALL with the --production flag, but its then running NPM POST INSTALL, which is generating the error. 

Ideally it would be good to avoid the hugo install script from running to speed up build times. 
Also as netlify does not need access to hugo, as this file has already been required by the netlify.toml file
(hugo is redundant, therefore devDependency)

Any ideas?

**Comment by sean-pwd** [comment]
I put in a request to hugo-installer to add this as an option as I couldn't find a clean way to implement this without writing a js node script.

**Comment by h-enk** [comment]
Good one. There's also no Netlify setting for `--ignore-scripts`. Also raise issue Netlify?

**Comment by h-enk** [comment]
Main issue is with Netlify running the postinstall script not properly/NOK. Also keep in mind I'd like to keep dev/prod parity (as much as possible).

**Comment by sean-pwd** [comment]
+1 for parity
I am only trying to remove packages that are redundant when netlify is
building.

**Comment by sean-pwd** [comment]
I added a new commit. 
I used a dependency called if-env for cross platform detection of node_env. 
I put in the request at hugo and this was the recommendation.

The PR should pass this time.

**Comment by h-enk** [comment]
@sean-pwd, I've been giving this another thought. I'd like to keep the production workflow in line w/ the development workflow as much as possible (dev/prod parity).

`hugo-installer` now installs in `node_modules/.bin/hugo` — this folder is cached by Netlify. It now works both locally + on Netlify (or any other host).

Why I like to use `hugo-installer` locally (on project level)? I wrote a little piece about that, here's a quote:

> If we could install Hugo locally as a dependency, we would have full control over the Hugo version used in our project. And best of all, all our project users would use the same version.
>
> [Managing Dependencies — Integrating with Hugo](https://henkverlinde.com/managing-dependencies/#integrating-with-hugo)

I did some tests on Netlify build times:

- Initial Netlify deploy (runs `npm i`) of `h-enk/hyas` takes 53s: https://app.netlify.com/sites/hyas/deploys/6126512d6745b9e20afaa832
- Repeat Netlify deploy (using cached `node_modules` folder) of `h-enk/hyas` takes 26s: https://app.netlify.com/sites/hyas/deploys/612651067266a00007c66091

I don't think splitting dependencies in dev + prod for speeding up Netlify initial deploys is a good idea. That way devDependencies are not really devDependencies anymore (same goes for dependencies). I think, for a Hugo (SSG) website, all dependencies are in effect devDependencies (that's why I set it up like so). Also, I think the issue this PR tries to solve, is not really a big issue (because repeat deploys use caching).

Note, there are also other ways to speed up Netlify deployments (significantly), e.g. switching off Netlify Forms detection (if not needed).

See also:
- https://answers.netlify.com/t/deploy-hugo-website-always-fails-when-caching-is-used/42997
- https://github.com/h-enk/hyas/issues/151#issuecomment-905553999
- https://discourse.gohugo.io/t/netlify-tip-turn-off-form-detection-if-you-dont-use-it/29160

**Pull request closed without merging**
