### PR TITLE
Esbuild

### PR DESCRIPTION
**Pull request by sean-pwd**
Created esbuild partial (see instructions in partial for how to use)
Removed module imports in hugo config
Created js files for importing individual modules
Js files are processed in script-footer.html

Tested and working

### CODE REVIEW

**Comment by h-enk** [comment]
https://deploy-preview-155--hyas.netlify.app/

**Comment by sean-pwd** [comment]
it appears to function perfectly on the netlify preview. Are you happy with the way I formatted the code?

**Review by h-enk — CHANGES_REQUESTED** [review]
Nice work! I really like the module import setup, examples + esbuild partial. Smart.

Two things. To minimise the number of browser requests, I'd like to see the smaller javascript files combined. So, lazysizes + instantpage into assets.js (I'd prefer main.js), and bootstrap.js separate.

ESLint error: https://github.com/h-enk/hyas/pull/155/checks?check_run_id=3074097096

**Comment by sean-pwd** [comment]
Are you ok with instant.page loading in the development environment?

I noticed you are currently only loading it for production.

I don't know a way of checking the environment from within a JS file so I
would have to set it up so instant.page and lazysizes both load all the
time.

**Comment by sean-pwd** [comment]
I have made the changes (with instant.page always loading), and pushed to my fork but I can't figure out why github hasn't picked it up.

**Comment by h-enk** [comment]
> Are you ok with instant.page loading in the development environment? I noticed you are currently only loading it for production. I don't know a way of checking the environment from within a JS file so I would have to set it up so instant.page and lazysizes both load all the time.

I'm OK w/ that, I think it's even better — for dev/prod parity.

**Comment by sean-pwd** [comment]
My most recent commit makes the link that hugo server produces clickable and relurls still work fine on server

**Comment by h-enk** [comment]
@sean-pwd, thanks a lot!

**Pull request merged**
